import { type NextPage } from "next";
import Head from "next/head";
import ChatBot from "../components/chatBot";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Help Chat Bot</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen w-full flex-col items-center justify-center">
        <ChatBot />
      </main>
    </>
  );
};

export default Home;
